# Site settings
title: Greeley Downtown Development Authority
email: team@variantstudios.com
description: 
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://long-jay1.cloudvent.net" # the base hostname & protocol for your site
timezone: America/Denver

# Site Author(s)
author:
  name: Brent Robbins
  email: brent@variantstudios.com
  name: Michael McQueen
  email: michael@variantstudios.com


# Build settings
highlighter: pygments
markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..6


# Permalinks
permalink: /news/:year-:month-:day/:title/


#Collections
collections:
  posts:
    output: false
  directory:
    output: true
    permalink: /directory/:title/
  service_categories:
    output: false
    permalink: /service-categories/:title/
  retail_categories:
    output: false
    permalink: /retail-categories/:title/
  nightlife_categories:
    output: false
    permalink: /nightlife-categories/:title/
  entertainment_and_recreation_categories:
    output: false
    permalink: /entertainment-and-recreation-categories/:title/ 
  dining_categories:
    output: false
    permalink: /dining_categories/:title/
  lodging_and_event_centers_categories:
    output: false
    permalink: /lodging-and-event-centers-categories/:title/
  properties:
    output: true
    permalink: /properties/:title/
  gallery:
    output: true
    permalink: /gallery/:title/
#Defaults
defaults:
  -
    scope:
      type: "directory"
    values:
      layout: "directory"
      sitemap:
        exclude: "no"
  -
    scope:
      type: "properties"
    values:
      layout: "property"
      sitemap:
        exclude: "no"

sale-or-leases:
  - Sale
  - Lease
  - Sale and Lease

property-types:
  - Commercial
  - Residential

sub-navs:
  - explore
  - play
  - work
  - more


# Blog Settings
paginate: 3
paginate_path: "/blog/page:num/"

# Reading Time Feature
reading_time:     true
words_per_minute: 200

# Disqus Comments
disqus_short_name: 
disqus_show_comment_count: 

# typekit
typekit: fza1iaf

# Social Media
facebook: 

# Google Analytics - UA-22056399-2
google_analytics_tracking_id: 

exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]

header_fallback_image_path: 'https://unsplash.it/1400/500'  